version: "3.9"
services:
  litellm:
    image: ghcr.io/berriai/litellm:main-stable
    ports: [ "4000:4000" ]
    volumes:
      - ./litellm_config.yaml:/app/config.yaml:ro
    environment:
      - AZURE_API_KEY=
      - AZURE_API_BASE=
    command: [ "--config", "/app/config.yaml", "--port", "4000" ]
